#!/bin/sh

# Configure Cloudreve
sed -i "s|PORT|${PORT}|g;s|SECRET|${Secret}|g" /workdir/conf.ini
ln -s /usr/bin/cloudreve /usr/bin/${EXEC}

# Run cloudreve
sv start 1 || exit 1
sv start redis || exit 1
exec 2>&1
exec ${EXEC} -c /workdir/conf.ini
